version: '3.8'
services:
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  nats:
    image: nats:2.10
    command: ["-c", "/etc/nats/nats.conf"]
    ports:
      - "4222:4222"
      - "9222:9222"
      - "8222:8222"
    volumes:
      - ./nats.conf:/etc/nats/nats.conf:ro


volumes:
  mongo_data:
